[workspace]

members = [
    "server",
    "app"
]

  [workspace.dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.6.18"
dotenv = "0.15.0"


[dev-dependencies]
openssl = "0.10.38"
crossbeam-channel = "0.3.9"
pkg-config = "0.3.16"
hkdf = "0.12.3"
p384 = "0.11.2"
